# Generated by Django 5.2.4 on 2025-07-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='一级配置')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='二级配置')),
                ('primary_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_configurations', to='deco_select.primaryconfiguration', verbose_name='所属一级配置')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100, verbose_name='型号')),
                ('product_type', models.CharField(max_length=100, verbose_name='梯型')),
                ('primary_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deco_select.primaryconfiguration', verbose_name='一级配置')),
                ('secondary_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deco_select.secondaryconfiguration', verbose_name='二级配置')),
            ],
        ),
    ]
