# Generated by Django 5.2.4 on 2025-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='细节图1'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_1_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='细节图1名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='细节图2'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='细节图2名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='细节图3'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image_3_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='细节图3名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='主图'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主图名称'),
        ),
    ]
