# Generated by Django 5.2.4 on 2025-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0002_product_detail_image_1_product_detail_image_1_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_configuration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_configuration',
        ),
        migrations.AddField(
            model_name='product',
            name='primary_configurations',
            field=models.ManyToManyField(blank=True, related_name='products', to='deco_select.primaryconfiguration', verbose_name='一级配置'),
        ),
        migrations.AddField(
            model_name='secondaryconfiguration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='secondary_configurations/', verbose_name='图片'),
        ),
    ]
