# Generated by Django 5.2.4 on 2025-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0003_remove_product_primary_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_configurations',
        ),
        migrations.RemoveField(
            model_name='secondaryconfiguration',
            name='primary_configuration',
        ),
        migrations.AddField(
            model_name='product',
            name='configurations',
            field=models.JSONField(blank=True, default=list, verbose_name='产品配置'),
        ),
        migrations.DeleteModel(
            name='PrimaryConfiguration',
        ),
        migrations.DeleteModel(
            name='SecondaryConfiguration',
        ),
    ]
