# Generated by Django 5.2.4 on 2025-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0004_remove_product_primary_configurations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='风格'),
        ),
    ]
