# Generated by Django 5.2.4 on 2025-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0005_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='文件名')),
                ('image', models.ImageField(upload_to='static_assets/', verbose_name='图片')),
            ],
        ),
    ]
