# Generated by Django 5.2.4 on 2025-08-06 08:09

import deco_select.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0006_staticasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preset',
            field=models.CharField(default='标配', max_length=100, verbose_name='预设配置'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=deco_select.models.product_image_upload_path, verbose_name='细节图1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=deco_select.models.product_image_upload_path, verbose_name='细节图2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=deco_select.models.product_image_upload_path, verbose_name='细节图3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=deco_select.models.product_image_upload_path, verbose_name='主图'),
        ),
    ]
