# Generated by Django 5.2.4 on 2025-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0007_product_preset_alter_product_detail_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='COP名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cops/', verbose_name='COP图片')),
            ],
        ),
    ]
