# Generated by Django 5.2.4 on 2025-08-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0008_cop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deco_select.cop', verbose_name='操纵箱（COP）'),
        ),
    ]
