# Generated by Django 5.2.4 on 2025-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0009_product_cop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default',
            field=models.BooleanField(default=False, verbose_name='是否默认型号配置'),
        ),
    ]
