# Generated by Django 5.2.4 on 2025-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0010_product_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='configurations',
        ),
        migrations.AddField(
            model_name='product',
            name='ceiling',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='吊顶'),
        ),
        migrations.AddField(
            model_name='product',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地坪'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_wall',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='前壁'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_wall',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='后壁'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_wall',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='侧壁'),
        ),
    ]
