# Generated by Django 5.2.4 on 2025-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0011_remove_product_configurations_product_ceiling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('product_id', models.IntegerField(verbose_name='产品ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='选择时间')),
            ],
        ),
    ]
