# Generated by Django 5.2.4 on 2025-08-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deco_select', '0012_userselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userselection',
            options={'ordering': ['-timestamp'], 'verbose_name': '用户选配记录', 'verbose_name_plural': '用户选配记录'},
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='product_id',
        ),
        migrations.AddField(
            model_name='userselection',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deco_select.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='snapshot_default',
            field=models.BooleanField(default=False, verbose_name='快照-是否默认'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='snapshot_model_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快照-型号'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='snapshot_preset',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快照-预设配置'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='snapshot_product_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快照-梯型'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='snapshot_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快照-风格'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='选择时间'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='user_id',
            field=models.IntegerField(db_index=True, verbose_name='用户ID'),
        ),
    ]
